WestSprings/Controllers/DirectoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WestSprings.Models;

namespace WestSprings.Controllers
{
    public class DirectoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Directories
        public ActionResult Index()
        {
            return View(db.Directories.ToList());
        }

        // GET: Directories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Directory directory = db.Directories.Find(id);
            if (directory == null)
            {
                return HttpNotFound();
            }
            return View(directory);
        }

        // GET: Directories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Directories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Directory directory)
        {
            if (ModelState.IsValid)
            {
                db.Directories.Add(directory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(directory);
        }

        // GET: Directories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Directory directory = db.Directories.Find(id);
            if (directory == null)
            {
                return HttpNotFound();
            }
            return View(directory);
        }

        // POST: Directories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind] Directory directory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(directory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(directory);
        }

        // GET: Directories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Directory directory = db.Directories.Find(id);
            if (directory == null)
            {
                return HttpNotFound();
            }
            return View(directory);
        }

        // POST: Directories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Directory directory = db.Directories.Find(id);
            db.Directories.Remove(directory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WestSprings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - West Springs Church</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'1e6e446a-4d30-4ac7-b196-3d488d227fa1'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>

@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{<div id="nav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <img id="headpic" src="~/Images/West Springs Cross.png" />
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("West Springs Church", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Start</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About Us", "About", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Statements", "Statements", "Home")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Connect</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Our Ministries", "Ministries", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Online Sermons", "Sermons", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Contact")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Serve</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Ongoing Opporitunities", "OngoingOpp", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Give", "Give", "Home")</li>
                    <li>@Html.ActionLink("Calendar", "ComingSoon", "Home")</li>
                    <li>@Html.ActionLink("Directory", "Index", "Directories")</li>

                </ul>

                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container body-content" id="body">
        @RenderBody()
        <hr />
        <footer>
            <div>
                &copy; @DateTime.Now.Year - 2016 West Springs Church | 501 Big Bend Rd, Ballwin, MO, 63021 | 636.394.7100
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false) }
else
{
    <div id="nav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <img id="headpic" src="~/Images/West Springs Cross.png" />
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("West Springs Church", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Start</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About Us", "About", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Statements", "Statements", "Home")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Connect</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Our Ministries", "Ministries", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Online Sermons", "Sermons", "Home")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Contact")</li>
                            </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Serve</a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Ongoing Opporitunities", "OngoingOpp", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Give", "Give", "Home")</li>
                    <li>@Html.ActionLink("Calendar", "ComingSoon", "Home")</li>
                    </ul>   
                        
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" id="body">
        @RenderBody()
        <hr />
        <footer>
            <div>
                &copy; @DateTime.Now.Year - West Springs Church | 501 Big Bend Rd, Ballwin, MO, 63021 | 636.394.7100
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
}x
</body>
</html>